### ISSUE TITLE
Xdebug?

### ISSUE THREAD

**Issue by kayakr** [Islandora-Devops/isle-site-template#17]
I'm not clear how to get xdebug operational. There is config at `/etc/php81/conf.d/50_xdebug.ini` where the PHP component is disabled, and there is an environment variable at https://github.com/Islandora-Devops/isle-site-template/blob/917e9cdce7a1f7f2a447ca248ac334becd2b3dd4/docker-compose.yml#L407 but it's not clear to me how these interact... Can you provide documentation?

**Comment by rosiel** [comment]
As far as I've learned, when you're using the built-in IDE at ide.islandora.dev or whatever your domain is, you can click the "Debug" buttons until a coloured banner appears, and then you can line-by-line debug as usual. 

The docs repeatedly mention an integration with PHPstorm but I've never seen that in practice.
