### ISSUE TITLE
User's run folder changes on reboot when using docker-compose.override.yml 

### ISSUE THREAD

**Issue by aOelschlager** [Islandora-Devops/isle-site-template#30]
I recently started testing out the isle-site-template but I didn't reboot my computer until yesterday. I noticed issues with my audio not working and I was getting an error after running systemctl --user. I eventually found this error message:

Runtime directory '/run/user/1000' is not owned by UID 1000, as it should.

When I checked the ownership, it ended up being root. I did come across another [repository](https://github.com/docker/for-linux/issues/1074) that had the [same issue](https://github.com/docker/for-linux/issues/1074#issuecomment-1908918943) with almost the same docker-compose file as the override file with the exception of the restart policy. They noticed it with Ubuntu 20.04 but I am running Pop!_OS 22.04.

My temporary fix was to stop running isle-site-template containers and change the ownership back to my user in the /run/user/1000 directory. Then I rebooted the laptop and my audio was working again.

**Comment by nigelgbanks** [comment]
Super strange, but we cannot provide the same workaround they used in the linked issue. By bind mounting, the ssh keys as read only, as we do not know which keys a user will use. Though, you are free to use that solution in your override file.

**Comment by nigelgbanks** [comment]
Thanks for highlighting the issue, if another runs into it, the information you have provided will definitely help them.

**Comment by aOelschlager** [comment]
Thanks Nigel for the explanation and reviewing the issue. I really appreciate it!
