### ISSUE TITLE
Missing dependency: wget, git

### ISSUE THREAD

**Issue by MykalMachon** [Islandora-Devops/isle-site-template#33]
## Summary of issue
I'm setting up a test Islandora site for evaluation on a RHEL 8 virtual machine. I was following the install guide, had installed the listed required tools, and ran the installer. A few prompts in, I received an error: `environment: line 115: wget: command not found`. This implies that you need `wget` on your system to run the installer. `wget` is not in [the listed requirements in the `README.md`](https://github.com/Islandora-Devops/isle-site-template?tab=readme-ov-file#requirements). 

**Does it make sense to list `wget` as an additional dependency in the `README.md`?** I know it's a pretty standard tool but it's not bundled with every distro by default (RHEL 8 does not include it, for example). edit: git is also like this, it is required by this script but not listed anywhere. 

I am more than happy to make a PR as this is a really simple change was just hoping for some input from the maintainers before doing so 😄

**Comment by joecorall** [comment]
Thanks for the report @MykalMachon! I just opened a PR to get these changes in.

**Comment by MykalMachon** [comment]
Thank you @joecorall !
