### ISSUE TITLE
Islandora Models Taxonomy Missing After Installation on Ubuntu 24.04

### ISSUE THREAD

**Issue by novacellus** [Islandora-Devops/isle-site-template#53]
After installing Islandora on a local Ubuntu 24.04 machine using both ISLE-DC and ISLE Site Template methods, the "Islandora Models" taxonomy is missing. The vocabulary does not appear in the "Create Repository Item" page (the select dropdown list is empty) or on the "Taxonomy Management" page.

**Steps to Reproduce**
1. Install Islandora on Ubuntu 24.04 using ISLE-DC or ISLE Site Template.
2. Navigate to the "Create Repository Item" page.
3. Attempt to select a model from the "Islandora Models" dropdown list.
4. Check the "Taxonomy Management" page for the "Islandora Models" vocabulary.
![obraz](https://github.com/user-attachments/assets/bdccd3a2-d439-47cb-ba4f-3c2ac4c43279)
![obraz](https://github.com/user-attachments/assets/c4510bff-cdcc-4d91-9036-ea97864a07ca)

**Comment by rosiel** [comment]
The installation methods haven't yet been tested (other than to find that they fail) with Ubuntu 24.04. 

If you want to repair your installation, you could try 

`drush migrate:import --userid=1 --tag=islandora`

however, the fact that that did not run suggests there is something deeper wrong.

**Comment by joecorall** [comment]
Thanks for reporting this @novacellus . This should be fixed on the main branch in this repo if you try again from scratch. This was a similar issue as https://github.com/Islandora-Devops/isle-site-template/issues/46
